WEATHER_API_KEY = "f4ed27622e29484a8c342846251210"
GROQ_API_KEY = "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"

TWITTER_API_KEY = "OMQqc5K4ilbWz3Us9SKvg8Yta"
TWITTER_API_KEY_SECRET = "eXoOOSk2eaJ0NfwZ6cNhORRFbIaKPgAavyU7KzO9OyjH5cohwa"
TWITTER_ACCESS_TOKEN = "1845850146107703297-m4NSBzgPdjDC48XFqAyGznHoHJK5Zj"
TWITTER_ACCESS_TOKEN_SECRET = "k88a9zqXXvoS41k5Nus5gDbCiHK2tshWHYQ0MuE1g9z1W"
