WEATHER_API_KEY = "f4ed27622e29484a8c342846251210"
GROQ_API_KEY = "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"

TWITTER_API_KEY = "cMJIivsDEpvv8sbvvm5jSUAIZ"
TWITTER_API_KEY_SECRET = "N3brDG386I7xyYJSLptwmm4bYBFJcZcNEvZJ5XHXmkOC6iyllq"
TWITTER_ACCESS_TOKEN = "1845850146107703297-8YkAu3JZmw9JrzH0gBGSTo7sOnXikQ"
TWITTER_ACCESS_TOKEN_SECRET = "FBeUdPC5NDBZIDPaZcNDM7GZI8Dh83gXE8OKQfgINUhwx"
